### ISSUE TITLE
cannot excute sql?

### ISSUE THREAD

**Issue by tian584092** [Helias/Keira2#22] opened 2015-11-11 04:15 UTC
cannot excute sql?

**Comment by tkrokli** [comment] 2015-11-11 07:10
Please provide more details, so we can write a good reply and possibly a solution, when we know what you are referring to. Is this about A) the online version, or B) a local configuration on your computer?

**Comment by tian584092** [comment] 2015-11-11 07:49
we've been testing with Keira2, I wonder does it only generate sql commands? or can it manipulate the database itself?

**Comment by tkrokli** [comment] 2015-11-11 08:42
OK, thanks for writing a more complete question.
*Short answer:* Keira2 can only generate SQL (text) output to screen (web page). No DB editing.

These 2 reasons should explain why it currently is unable to manipulate the DB:
- The feature is not yet implemented, the functionality is a planned (future) feature.
- Existing methods are not considered safe enough for direct database editing.

See also my reply in issue https://github.com/Helias/Keira2/issues/20#issuecomment-146694934 where I wrote a similar post, confirmed by ShinDarth.

**Comment by tian584092** [comment] 2015-11-11 08:57
thx

**Comment by ShinDarth** [comment] 2015-11-11 09:03
just copy and paste the SQL code generated by Keira2 to whatever MySQL client.

Duplicate of https://github.com/Helias/Keira2/issues/15 closing.

**Closed by ShinDarth** 2015-11-11 09:03 UTC
