### ISSUE TITLE
Execute SQL Script

### ISSUE THREAD

**Issue by slyceRgermany** [Helias/Keira2#24] opened 2015-12-27 22:26 UTC
First, great work!
Its planned to integrate a "Execute SQL" Button?

Greets

**Comment by ShinDarth** [comment] 2015-12-27 22:34
Thanks.  Yes it is planned. We are a bit busy in RL so it will take a while. 

Closing this because duplicate of https://github.com/Helias/Keira2/issues/15

**Closed by ShinDarth** 2015-12-27 22:34 UTC
